### ISSUE TITLE
Not Connecting to Server

### ISSUE THREAD

**Issue by hlebron1** [bitfocus/companion-module-lyntec-rpc-breaker#1]
I installed this in my companion modules, and I am not sure what I may be doing wrong.

The stats for my RPC unit are: 

- Hardware Version: | 1.03a
- Firmware Version: | 1.20a3
- Web Version: | 1.20

What steps do I need to do to trouble shoot the connection?

Thanks!

**Comment by murphytodd4** [comment]
@hlebron1 can you telnet into your lyntec RPC panel? When you connect it should present you something along the lines of "LynTec Telnet Server x.xx". If that is not 1.01 you may have to contact LynTec and get a software update from them. This module was developed on hardware version 2.0, firmware version 2.73a, and telnet server 1.01.
